config/routes.rb
GalaxyWars::Application.routes.draw do
  resources :moons

  resources :planets

  resources :stars
      match ':stars/:id/near' =>'stars#near'

end

app/models/aliance.rb
class Aliance < ActiveRecord::Base
  attr_accessible :name
end

app/models/moon.rb
class Moon < ActiveRecord::Base
  belongs_to :planet
  belongs_to :aliance
  belongs_to :user
  attr_accessible :planet_id, :user_id, :aliance_id, :amoniate, :atmosphere, :carbone, :fissionable_material, :habitables, :mass, :mediumtemp, :metal, :metal_cristal, :n_p, :organicA, :organicB, :organicC, :position, :tipo, :water
end

app/models/planet.rb
class Planet < ActiveRecord::Base
  belongs_to :star
  belongs_to :aliance
  belongs_to :user
  has_many :moons
 attr_accessible :star_id,:user,:aliance, :amoniate, :atmosphere, :carbone, :fissionable_material, :habitables, :mass, :mediumtemp, :metal, :metal_cristal, :n_p, :organicA, :organicB, :organicC, :position, :tipo, :water
  validates :star,presence: true

end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :aliance
  belongs_to :user
  has_many :planets
  attr_accessible :aliance_id,:user_id, :clase, :color, :cool_line, :hot_line, :intern_line, :luminosity, :mass, :name, :near, :radium, :snow_line, :temp, :x, :y, :z

  validates :name, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :aliance
  attr_accessible :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 after_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/controllers/moons_controller.rb
class MoonsController < ApplicationController
  # GET /moons
  # GET /moons.json
  def index
    @moons = Moon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moons }
    end
  end

  # GET /moons/1
  # GET /moons/1.json
  def show
    @moon = Moon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moon }
    end
  end

  # GET /moons/new
  # GET /moons/new.json
  def new
    @moon = Moon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moon }
    end
  end

  # GET /moons/1/edit
  def edit
    @moon = Moon.find(params[:id])
  end

  # POST /moons
  # POST /moons.json
  def create
    @moon = Moon.new(params[:moon])

    respond_to do |format|
      if @moon.save
        format.html { redirect_to @moon, notice: 'Moon was successfully created.' }
        format.json { render json: @moon, status: :created, location: @moon }
      else
        format.html { render action: "new" }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moons/1
  # PUT /moons/1.json
  def update
    @moon = Moon.find(params[:id])

    respond_to do |format|
      if @moon.update_attributes(params[:moon])
        format.html { redirect_to @moon, notice: 'Moon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @moon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moons/1
  # DELETE /moons/1.json
  def destroy
    @moon = Moon.find(params[:id])
    @moon.destroy

    respond_to do |format|
      format.html { redirect_to moons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @planets }
    end
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
    @planet = Planet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @planet }
    end
  end

  # GET /planets/new
  # GET /planets/new.json
  def new
    @planet = Planet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @planet }
    end
  end

  # GET /planets/1/edit
  def edit
    @planet = Planet.find(params[:id])
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(params[:planet])

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render json: @planet, status: :created, location: @planet }
      else
        format.html { render action: "new" }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /planets/1
  # PUT /planets/1.json
  def update
    @planet = Planet.find(params[:id])

    respond_to do |format|
      if @planet.update_attributes(params[:planet])
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet = Planet.find(params[:id])
    @planet.destroy

    respond_to do |format|
      format.html { redirect_to planets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stars }
    end
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
    @star = Star.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @star }
    end
  end
  def near
    @star = Star.find(params[:id])
    @nearstars = Array.new
    @star.near.scan(/(\d+),(\d+)/).each do |nearstar|
        @nearstars.push({'star'=>Star.find(nearstar[0]),'distance'=>nearstar[1]})
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nearstars }
    end

  end

  # GET /stars/new
  # GET /stars/new.json
  def new
    @star = Star.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @star }
    end
  end

  # GET /stars/1/edit
  def edit
    @star = Star.find(params[:id])
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(params[:star])

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render json: @star, status: :created, location: @star }
      else
        format.html { render action: "new" }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stars/1
  # PUT /stars/1.json
  def update
    @star = Star.find(params[:id])

    respond_to do |format|
      if @star.update_attributes(params[:star])
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star = Star.find(params[:id])
    @star.destroy

    respond_to do |format|
      format.html { redirect_to stars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moons_helper.rb
module MoonsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GalaxyWars</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moons/_form.html.erb
<%= form_for(@moon) do |f| %>
  <% if @moon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moon.errors.count, "error") %> prohibited this moon from being saved:</h2>

      <ul>
      <% @moon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :planet %><br />
    <%= f.collection_select :planet_id, Planet.all, :id, :id  %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :mass %><br />
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.number_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :atmosphere %><br />
    <%= f.number_field :atmosphere %>
  </div>
  <div class="field">
    <%= f.label :metal %><br />
    <%= f.number_field :metal %>
  </div>
  <div class="field">
    <%= f.label :water %><br />
    <%= f.number_field :water %>
  </div>
  <div class="field">
    <%= f.label :amoniate %><br />
    <%= f.number_field :amoniate %>
  </div>
  <div class="field">
    <%= f.label :carbone %><br />
    <%= f.number_field :carbone %>
  </div>
  <div class="field">
    <%= f.label :n_p %><br />
    <%= f.number_field :n_p %>
  </div>
  <div class="field">
    <%= f.label :fissionable_material %><br />
    <%= f.number_field :fissionable_material %>
  </div>
  <div class="field">
    <%= f.label :mediumtemp %><br />
    <%= f.number_field :mediumtemp %>
  </div>
  <div class="field">
    <%= f.label :aliance %><br />
    <%= f.text_field :aliance %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :organicA %><br />
    <%= f.number_field :organicA %>
  </div>
  <div class="field">
    <%= f.label :organicB %><br />
    <%= f.number_field :organicB %>
  </div>
  <div class="field">
    <%= f.label :organicC %><br />
    <%= f.number_field :organicC %>
  </div>
  <div class="field">
    <%= f.label :metal_cristal %><br />
    <%= f.number_field :metal_cristal %>
  </div>
  <div class="field">
    <%= f.label :habitables %><br />
    <%= f.number_field :habitables %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moons/edit.html.erb
<h1>Editing moon</h1>

<%= render 'form' %>

<%= link_to 'Show', @moon %> |
<%= link_to 'Back', moons_path %>

app/views/moons/index.html.erb
<h1>Listing moons</h1>

<table>
  <tr>
    <th>Planet</th>
    <th>Position</th>
    <th>Mass</th>
    <th>Type</th>
    <th>Atmosphere</th>
    <th>Metal</th>
    <th>Water</th>
    <th>Amoniate</th>
    <th>Carbone</th>
    <th>N p</th>
    <th>Fissionable material</th>
    <th>Mediumtemp</th>
    <th>Alliance</th>
    <th>User</th>
    <th>Organica</th>
    <th>Organicb</th>
    <th>Organicc</th>
    <th>Metal cristal</th>
    <th>Habitables</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moons.each do |moon| %>
  <tr>
    <td><%= link_to moon.planet,moon_planet %></td>
    <td><%= moon.position %></td>
    <td><%= moon.mass %></td>
    <td><%= moon.tipo %></td>
    <td><%= moon.atmosphere %></td>
    <td><%= moon.metal %></td>
    <td><%= moon.water %></td>
    <td><%= moon.amoniate %></td>
    <td><%= moon.carbone %></td>
    <td><%= moon.n_p %></td>
    <td><%= moon.fissionable_material %></td>
    <td><%= moon.mediumtemp %></td>
    <td><%= moon.aliance %></td>
    <td><%= moon.user %></td>
    <td><%= moon.organicA %></td>
    <td><%= moon.organicB %></td>
    <td><%= moon.organicC %></td>
    <td><%= moon.metal_cristal %></td>
    <td><%= moon.habitables %></td>
    <td><%= link_to 'Show', moon %></td>
    <td><%= link_to 'Edit', edit_moon_path(moon) %></td>
    <td><%= link_to 'Destroy', moon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moon', new_moon_path %>

app/views/moons/new.html.erb
<h1>New moon</h1>

<%= render 'form' %>

<%= link_to 'Back', moons_path %>

app/views/moons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Planet:</b>
  <%= @moon.planet %>
</p>

<p>
  <b>Position:</b>
  <%= @moon.position %>
</p>

<p>
  <b>Mass:</b>
  <%= @moon.mass %>
</p>

<p>
  <b>Type:</b>
  <%= @moon.tipo %>
</p>

<p>
  <b>Atmosphere:</b>
  <%= @moon.atmosphere %>
</p>

<p>
  <b>Metal:</b>
  <%= @moon.metal %>
</p>

<p>
  <b>Water:</b>
  <%= @moon.water %>
</p>

<p>
  <b>Amoniate:</b>
  <%= @moon.amoniate %>
</p>

<p>
  <b>Carbone:</b>
  <%= @moon.carbone %>
</p>

<p>
  <b>N p:</b>
  <%= @moon.n_p %>
</p>

<p>
  <b>Fissionable material:</b>
  <%= @moon.fissionable_material %>
</p>

<p>
  <b>Mediumtemp:</b>
  <%= @moon.mediumtemp %>
</p>

<p>
  <b>Alliance:</b>
  <%= @moon.alliance %>
</p>

<p>
  <b>User:</b>
  <%= @moon.user %>
</p>

<p>
  <b>Organica:</b>
  <%= @moon.organicA %>
</p>

<p>
  <b>Organicb:</b>
  <%= @moon.organicB %>
</p>

<p>
  <b>Organicc:</b>
  <%= @moon.organicC %>
</p>

<p>
  <b>Metal cristal:</b>
  <%= @moon.metal_cristal %>
</p>

<p>
  <b>Habitables:</b>
  <%= @moon.habitables %>
</p>


<%= link_to 'Edit', edit_moon_path(@moon) %> |
<%= link_to 'Back', moons_path %>

app/views/planets/_form.html.erb
<%= form_for(@planet) do |f| %>
  <% if @planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% @planet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :star %><br />
    <%= f.collection_select :star_id, Star.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :mass %><br />
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.number_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :atmosphere %><br />
    <%= f.number_field :atmosphere %>
  </div>
  <div class="field">
    <%= f.label :metal %><br />
    <%= f.number_field :metal %>
  </div>
  <div class="field">
    <%= f.label :water %><br />
    <%= f.number_field :water %>
  </div>
  <div class="field">
    <%= f.label :amoniate %><br />
    <%= f.number_field :amoniate %>
  </div>
  <div class="field">
    <%= f.label :carbone %><br />
    <%= f.number_field :carbone %>
  </div>
  <div class="field">
    <%= f.label :n_p %><br />
    <%= f.number_field :n_p %>
  </div>
  <div class="field">
    <%= f.label :fissionable_material %><br />
    <%= f.number_field :fissionable_material %>
  </div>
  <div class="field">
    <%= f.label :mediumtemp %><br />
    <%= f.number_field :mediumtemp %>
  </div>
  <div class="field">
    <%= f.label :aliance %><br />
    <%= f.collection_select :aliance_id, Aliance.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :organicA %><br />
    <%= f.number_field :organicA %>
  </div>
  <div class="field">
    <%= f.label :organicB %><br />
    <%= f.number_field :organicB %>
  </div>
  <div class="field">
    <%= f.label :organicC %><br />
    <%= f.number_field :organicC %>
  </div>
  <div class="field">
    <%= f.label :metal_cristal %><br />
    <%= f.number_field :metal_cristal %>
  </div>
  <div class="field">
    <%= f.label :habitables %><br />
    <%= f.number_field :habitables %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing planet</h1>

<%= render 'form' %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<h1>Listing planets</h1>

<table>
  <tr>
    <th>Star</th>
    <th>Position</th>
    <th>Mass</th>
    <th>Type</th>
    <th>Atmosphere</th>
    <th>Metal</th>
    <th>Water</th>
    <th>Amoniate</th>
    <th>Carbone</th>
    <th>N p</th>
    <th>Fissionable material</th>
    <th>Mediumtemp</th>
    <th>Aliance</th>
    <th>User</th>
    <th>Organica</th>
    <th>Organicb</th>
    <th>Organicc</th>
    <th>Metal cristal</th>
    <th>Habitables</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @planets.each do |planet| %>
  <tr>
    <td><%= link_to planet.star.name , planet.star %></td>
    <td><%= planet.position %></td>
    <td><%= planet.mass %></td>
    <td><%= planet.tipo %></td>
    <td><%= planet.atmosphere %></td>
    <td><%= planet.metal %></td>
    <td><%= planet.water %></td>
    <td><%= planet.amoniate %></td>
    <td><%= planet.carbone %></td>
    <td><%= planet.n_p %></td>
    <td><%= planet.fissionable_material %></td>
    <td><%= planet.mediumtemp %></td>
    <td><%= planet.aliance %></td>
    <td><%= planet.user %></td>
    <td><%= planet.organicA %></td>
    <td><%= planet.organicB %></td>
    <td><%= planet.organicC %></td>
    <td><%= planet.metal_cristal %></td>
    <td><%= planet.habitables %></td>
    <td><%= link_to 'Show', planet %></td>
    <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
    <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New planet</h1>

<%= render 'form' %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Star:</b>
  <%= link_to @planet.star.name, @planet.star %>
</p>

<p>
  <b>Position:</b>
  <%= @planet.position %>
</p>

<p>
  <b>Mass:</b>
  <%= @planet.mass %>
</p>

<p>
  <b>Type:</b>
  <%= @planet.tipo %>
</p>

<p>
  <b>Atmosphere:</b>
  <%= @planet.atmosphere %>
</p>

<p>
  <b>Metal:</b>
  <%= @planet.metal %>
</p>

<p>
  <b>Water:</b>
  <%= @planet.water %>
</p>

<p>
  <b>Amoniate:</b>
  <%= @planet.amoniate %>
</p>

<p>
  <b>Carbone:</b>
  <%= @planet.carbone %>
</p>

<p>
  <b>N p:</b>
  <%= @planet.n_p %>
</p>

<p>
  <b>Fissionable material:</b>
  <%= @planet.fissionable_material %>
</p>

<p>
  <b>Mediumtemp:</b>
  <%= @planet.mediumtemp %>
</p>

<p>
  <b>Alliance:</b>
  <%= @planet.aliance %>
</p>

<p>
  <b>User:</b>
  <%= @planet.user %>
</p>

<p>
  <b>Organica:</b>
  <%= @planet.organicA %>
</p>

<p>
  <b>Organicb:</b>
  <%= @planet.organicB %>
</p>

<p>
  <b>Organicc:</b>
  <%= @planet.organicC %>
</p>

<p>
  <b>Metal cristal:</b>
  <%= @planet.metal_cristal %>
</p>

<p>
  <b>Habitables:</b>
  <%= @planet.habitables %>
</p>


<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>

app/views/stars/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :z %><br />
    <%= f.number_field :z %>
  </div>
  <div class="field">
    <%= f.label :mass %><br />
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :radium %><br />
    <%= f.text_field :radium %>
  </div>
  <div class="field">
    <%= f.label :luminosity %><br />
    <%= f.text_field :luminosity %>
  </div>
  <div class="field">
    <%= f.label :temp %><br />
    <%= f.number_field :temp %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.number_field :color %>
  </div>
  <div class="field">
    <%= f.label :clase %><br />
    <%= f.text_field :clase %>
  </div>
  <div class="field">
    <%= f.label :aliance %><br />
    <%= f.collection_select :aliance_id, Aliance.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :near %><br />
    <%= f.text_area :near %>
  </div>
  <div class="field">
    <%= f.label :intern_line %><br />
    <%= f.text_field :intern_line %>
  </div>
  <div class="field">
    <%= f.label :hot_line %><br />
    <%= f.text_field :hot_line %>
  </div>
  <div class="field">
    <%= f.label :snow_line %><br />
    <%= f.text_field :snow_line %>
  </div>
  <div class="field">
    <%= f.label :cool_line %><br />
    <%= f.text_field :cool_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stars/edit.html.erb
<h1>Editing star</h1>

<%= render 'form' %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

app/views/stars/index.html.erb
<h1>Listing stars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>X</th>
    <th>Y</th>
    <th>Z</th>
    <th>Mass</th>
    <th>Radium</th>
    <th>Luminosity</th>
    <th>Temp</th>
    <th>Color</th>
    <th>Clase</th>
    <th>Aliance</th>
    <th>User</th>
    <th>Near</th>
    <th>Intern line</th>
    <th>Hot line</th>
    <th>Snow line</th>
    <th>Cool line</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stars.each do |star| %>
  <tr>
    <td><%= star.name %></td>
    <td><%= star.x %></td>
    <td><%= star.y %></td>
    <td><%= star.z %></td>
    <td><%= star.mass %></td>
    <td><%= star.radium %></td>
    <td><%= star.luminosity %></td>
    <td><%= star.temp %></td>
    <td><%= star.color %></td>
    <td><%= star.clase %></td>
    <td><%= star.aliance %></td>
    <td><%= star.user %></td>
    <td><%= star.near %></td>
    <td><%= star.intern_line %></td>
    <td><%= star.hot_line %></td>
    <td><%= star.snow_line %></td>
    <td><%= star.cool_line %></td>
    <td><%= link_to 'Show', star %></td>
    <td><%= link_to 'Edit', edit_star_path(star) %></td>
    <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Star', new_star_path %>

app/views/stars/new.html.erb
<h1>New star</h1>

<%= render 'form' %>

<%= link_to 'Back', stars_path %>

app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @star.name %>
</p>

<p>
  <b>X:</b>
  <%= @star.x %>
</p>

<p>
  <b>Y:</b>
  <%= @star.y %>
</p>

<p>
  <b>Z:</b>
  <%= @star.z %>
</p>

<p>
  <b>Mass:</b>
  <%= @star.mass %>
</p>

<p>
  <b>Radium:</b>
  <%= @star.radium %>
</p>

<p>
  <b>Luminosity:</b>
  <%= @star.luminosity %>
</p>

<p>
  <b>Temp:</b>
  <%= @star.temp %>
</p>

<p>
  <b>Color:</b>
  <%= @star.color %>
</p>

<p>
  <b>Clase:</b>
  <%= @star.clase %>
</p>

<p>
  <b>Aliance:</b>
  <%= @star.aliance %>
</p>

<p>
  <b>User:</b>
  <%= @star.user %>
</p>

<p>
  <b>Near:</b>
  <%= @star.near %>
</p>

<p>
  <b>Intern line:</b>
  <%= @star.intern_line %>
</p>

<p>
  <b>Hot line:</b>
  <%= @star.hot_line %>
</p>

<p>
  <b>Snow line:</b>
  <%= @star.snow_line %>
</p>

<p>
  <b>Cool line:</b>
  <%= @star.cool_line %>
</p>


<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>